### ISSUE TITLE
VM Tools fails when VM has VPN service installed

### ISSUE THREAD

**Issue by uvjim** [freenas/freenas-vm-tools#6]
Hi,

I have created a VM for installing OpenVPN Access Server in.  That all seems to be fine.  I've also added the freenas-vm-tools in there as well.  I have found however that when the openvpnas service is running then the VM tools service dies when it gets queried.

systemctl status reports the following...

```
● freenas-vm-tools.service - FreeNAS guest VM tools agent
   Loaded: loaded (/usr/lib/systemd/system/freenas-vm-tools.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sun 2017-03-19 16:50:26 GMT; 4min 38s ago
  Process: 1567 ExecStart=/usr/local/sbin/freenas-vm-tools (code=killed, signal=ABRT)
 Main PID: 1567 (code=killed, signal=ABRT)

Mar 19 16:46:05 vpnserver systemd[1]: Started FreeNAS guest VM tools agent.
Mar 19 16:46:05 vpnserver freenas-vm-tools[1567]: Plugin loaded: system
Mar 19 16:46:05 vpnserver freenas-vm-tools[1567]: Plugin loaded: file
Mar 19 16:46:05 vpnserver freenas-vm-tools[1567]: Plugin loaded: network
Mar 19 16:46:05 vpnserver freenas-vm-tools[1567]: Started
Mar 19 16:50:26 vpnserver systemd[1]: freenas-vm-tools.service: Main process exited, code=killed, status=6/ABRT
Mar 19 16:50:26 vpnserver systemd[1]: freenas-vm-tools.service: Unit entered failed state.
Mar 19 16:50:26 vpnserver systemd[1]: freenas-vm-tools.service: Failed with result 'signal'.

```
VM details are as follows: -
**Devices**
- NIC --> E1000 --> Bridged using lagg0
- DISK --> BLOCK --> 5GB --> AHCI
- OS: Ubuntu Server 16.04.2

I have noticed that the openvpnas service creates another network interface which obviously isn't listed in the devices section.  In my case this is named `as0t0` (not sure if that is relevant).

If you need anymore information just let me know.  I should add that I have two other servers (all cloned from the same VM) that are not exhibiting this issue which is why I believe it to do with the additional network interface.

Thanks in advance.

**Comment by 650elx** [comment]
Hi,

Can you create a ticket using our bug tracker at bugs.freenas.org ?

Please describe the exact VM you're using and attach some logs from it and assign it to me.

Thanks in advance,
Bartosz

**Comment by uvjim** [comment]
Created with ref: 22954.  I don't seem to be able to assign to you though.

**Comment by 650elx** [comment]
No problem; I've just reassigned this ticket.
